FROM node:21 as builder
WORKDIR /app
COPY ./login-page-main ./
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/login-page/browser /usr/share/nginx/html
COPY ./arquivos-virtuais-front/nginx.conf /etc/nginx/nginx.conf
COPY ./arquivos-virtuais-front/mime.types /etc/nginx/mime.types
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]